[tool.poetry]
name = "altairexpress"
version = "0.1.0"
description = "Python package that creates basic EDA graphics in Altair with ease."
authors = ["Lesley <iamthelm@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
altair = "^4.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
